/* ============================================================
   VOGELMATCH — soortendatabase
   Schalen 1–5 zijn kwalitatieve inschattingen (zie DATA_NOTE).
   Velden:
   size 1–5 · life [min,max] jaren bij goede zorg · noise 1–5
   handsOn: hoe handtam/knuffelbaar (potentie) · bond: menselijke-bandbehoefte
   clown: speelsheid · intel · train · activity · flight (behoefte/talent)
   social: behoefte aan gezelschap · pair: 'groep'|'paar'|'flex'|'solo'
   mess · bite · destruct · difficulty · space (1 klein kooitje … 5 volière/kamer)
   hours [min,max] dagelijkse interactie bij aanbevolen houderij
   beginner · cost (jaarlijks + dierenarts) · talk 0–5 · song 0–5
   bold: brutaal/territoriaal · ground: scharrelt op de grond · vsBirds: agressie naar andere soorten
   ============================================================ */

const DATA_NOTE = "Schalen 1–5 zijn kwalitatieve inschattingen, gebaseerd op de genoemde bronnen en ervaringskennis van aviaire dierenartsen, verenigingen en ervaren houders. Het zijn soortgemiddelden: individuele vogels verschillen sterk (opfok, socialisatie, hormonen, gezondheid). Levensduur is een bandbreedte bij goede zorg; de mediane levensduur in gevangenschap ligt bij veel papegaaien lager dan vaak wordt gedacht (Young e.a., 2012).";

const SOURCES = {
  licg: { t: "LICG – Landelijk InformatieCentrum Gezelschapsdieren (huisdierenbijsluiters)", u: "https://www.licg.nl" },
  licg_valk: { t: "LICG Huisdierenbijsluiter Valkparkiet", u: "https://professionals.licg.nl/lgp-dlbijsluiter?key=1507" },
  licg_gras: { t: "LICG Huisdierenbijsluiter Grasparkiet (houd met soortgenoot)", u: "https://professionals.licg.nl/media/5922/grasparkiet_bijsluiter6_22t.pdf" },
  young: { t: "Young, Hobson, Lackey & Wright (2012). Survival on the ark: life-history trends in captive parrots. Animal Conservation 15:28–43", u: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3289156" },
  wpt: { t: "World Parrot Trust – Parrot Encyclopedia & welzijnsinformatie", u: "https://www.parrots.org" },
  wpt_life: { t: "World Parrot Trust – ‘Long Live the Parrot’ (PsittaScene, 2012)", u: "https://parrots.org/wp-content/uploads/2025/02/Long-Live-the-Parrot.pdf" },
  lafeber: { t: "Lafeber Company – soortinformatie en verzorging (met aviaire dierenartsen)", u: "https://lafeber.com" },
  nbvv: { t: "NBvV – Standaard Valkparkiet (kleurslagen/mutaties), 2016–2025", u: "https://nbvv.nl/wp-content/uploads/Valkparkiet-2016-2025.pdf" },
  iplo: { t: "IPLO – Rijksregels invasieve uitheemse soorten (Unielijst)", u: "https://iplo.nl/regelgeving/regels-voor-activiteiten/activiteiten-natuur/invasieve-uitheemse-soorten-invasieve-exoten/rijksregels-invasieve-uitheemse-soorten-invasieve/" },
  sovon: { t: "Sovon / Kijk op Exoten nr. 49 (2025) – Parkieten in Nederland", u: "https://natuurtijdschriften.nl/pub/1030063/Exoten2025013002006.pdf" },
  eu2025: { t: "Uitvoeringsverordening (EU) 2025/1422 – update Unielijst invasieve exoten", u: "https://eur-lex.europa.eu/eli/reg_impl/2025/1422" },
  cites: { t: "CITES – Bijlagen I, II en III", u: "https://cites.org/eng/app/appendices.php" },
  merck: { t: "MSD/Merck Veterinary Manual – vogels: voeding, toxicologie (o.a. PTFE)", u: "https://www.merckvetmanual.com" }
};

// Kleurcodes voor de getekende ‘veldgidsplaat’
// keys: body, chest, belly, head, cap, cheek, wing, tail, beak, ring (nekband), eye(ring), crest
const SPECIES = [
// ---------------- Zang- en siervogels ----------------
{ id:"kanarie", nl:"Kanarie", sci:"Serinus canaria f. domestica", cat:"Zang- en siervogels", cm:"12–14 cm",
  size:1, life:[10,15], noise:1, noiseNote:"Zang (vooral mannen): melodieus, zelden schel.",
  handsOn:1, bond:1, clown:1, intel:2, train:1, activity:2, flight:3, social:2, pair:"solo",
  mess:2, bite:1, destruct:1, difficulty:1, space:2, hours:[0.25,0.5], beginner:5, cost:1, talk:0, song:5,
  slender:false, bold:1, ground:1, vsBirds:1, hormonal:2,
  tag:"De klassieke zanger: geniet van hem, knuffel hem niet.",
  pros:["Prachtige zang (mannen)","Weinig dagelijkse interactie nodig","Weinig lawaai buiten de zang","Een man kan prima alleen"],
  cons:["Kijk- en luistervogel, niet handtam","Stress bij vastpakken","Heeft een lange kooi nodig om te vliegen"],
  risks:["Mijten en huidproblemen","Gevoelig voor tocht, rook en dampen","Overgewicht bij alleen zaad"],
  pairNote:"Een zingende man houd je prima alleen. Twee mannen samen kunnen vechten; meerdere vogels = volière.",
  sexNote:"Vrijwel alleen mannen zingen volledig. Wil je zang, kies een man (herkenbaar aan zang of via DNA).",
  mut:[["Geel",{}],["Oranje/rood (rode factor)",{body:"#f08a3a",head:"#f08a3a",wing:"#d9702a",tail:"#c9652a"}],["Wit",{body:"#f6f4ee",head:"#f6f4ee",wing:"#e4e1d8",tail:"#dad6cc"}],["Groen (wildkleur-achtig)",{body:"#9db542",head:"#a9bf4f",wing:"#5c6b2e",tail:"#4f5a2a"}]],
  day:"Een lange kooi bij het licht (niet in de zon of tocht), een badje en wat groente. Jij geniet vooral van de ochtendzang.",
  c:{body:"#f5d33c",head:"#f5d33c",wing:"#e2b928",tail:"#d6a91f",beak:"#e8c9a0"}, beak:"cone", tail:"short",
  src:["licg","lafeber","merck"] },

{ id:"zebravink", nl:"Zebravink", sci:"Taeniopygia castanotis", cat:"Zang- en siervogels", cm:"10–11 cm",
  size:1, life:[5,9], noise:2, noiseNote:"Constant zacht ‘toeten’ en kwetteren; niet hard, wel aanwezig.",
  handsOn:1, bond:1, clown:2, intel:2, train:1, activity:4, flight:3, social:5, pair:"groep",
  mess:2, bite:1, destruct:1, difficulty:1, space:2, hours:[0.25,0.5], beginner:4, cost:1, talk:0, song:2,
  slender:false, bold:2, ground:2, vsBirds:2, hormonal:3,
  tag:"Druk, gezellig groepje om naar te kijken.",
  pros:["Levendig en grappig om te observeren","Weinig interactie met mensen nodig","Goedkoop in onderhoud"],
  cons:["Altijd minimaal een paar of groepje","Niet tam","Kweken gaat snel ongewenst door"],
  risks:["Eileg-problemen bij overmatig broeden","Mijten","Korte levensduur"],
  pairNote:"Nooit alleen. Een paar of een groepje (bijv. alleen mannen of alleen poppen als je niet wilt kweken).",
  sexNote:"Mannen hebben oranje wangen en zingen. Gemengde paren broeden vaak: geen nestgelegenheid als je niet wilt kweken.",
  mut:[["Grijs (wildkleur)",{}],["Wit",{body:"#f4f2ec",head:"#f4f2ec",wing:"#e8e5dd",tail:"#ddd8cf",cheek:"#f4f2ec"}],["Bruin/fawn",{head:"#a08672",wing:"#a8907b"}]],
  day:"Een groepje in een brede vlucht of kamervolière, met zaad, eivoer en groen. Jij kijkt, zij doen hun eigen ding.",
  c:{body:"#ddd5c8",chest:"#e9e4dc",head:"#8f8f93",cheek:"#e07a3a",wing:"#9b9086",tail:"#4a4a4a",beak:"#e2462b"}, beak:"cone", tail:"short",
  src:["licg","lafeber"] },

{ id:"japansemeeuw", nl:"Japanse meeuw", sci:"Lonchura striata f. domestica", cat:"Zang- en siervogels", cm:"11–12 cm",
  size:1, life:[5,10], noise:1, noiseNote:"Zacht gekwetter, nauwelijks storend.",
  handsOn:1, bond:1, clown:1, intel:2, train:1, activity:2, flight:3, social:5, pair:"groep",
  mess:2, bite:1, destruct:1, difficulty:1, space:2, hours:[0.25,0.5], beginner:5, cost:1, talk:0, song:2,
  slender:false, bold:1, ground:2, vsBirds:1, hormonal:2,
  tag:"De vredelievendste vink die er is.",
  pros:["Zeer verdraagzaam en rustig","Stil","Makkelijk en sterk"],
  cons:["Niet tam","Altijd met soortgenoten","Weinig ‘persoonlijkheid’ richting mensen"],
  risks:["Overgroei van nagels/snavel","Mijten"],
  pairNote:"Altijd minimaal twee; ze slapen graag tegen elkaar aan.",
  sexNote:"Uiterlijk nauwelijks te onderscheiden; mannen zingen. Voor een rustig koppel maakt het weinig uit.",
  mut:[["Bruinbont",{}],["Wit",{body:"#f6f4ee",head:"#f6f4ee",wing:"#efece4",tail:"#e4e0d8"}],["Chocolade",{head:"#5a3d2a",wing:"#6a4a32",body:"#c9b49a"}]],
  day:"Een rustig groepje in een vlucht, met een nestkastje om in te slapen. Ideaal als je weinig tijd hebt maar wel leven in huis wilt.",
  c:{body:"#e8e0d0",head:"#7a5a3e",wing:"#8a6b4c",tail:"#5d4632",beak:"#8c8c8c"}, beak:"cone", tail:"short",
  src:["licg","lafeber"] },

{ id:"gould", nl:"Gouldamadine", sci:"Chloebia (Erythrura) gouldiae", cat:"Zang- en siervogels", cm:"12–14 cm",
  size:1, life:[5,8], noise:1, noiseNote:"Zeer stil; zacht gesis en gezang.",
  handsOn:1, bond:1, clown:1, intel:2, train:1, activity:2, flight:3, social:4, pair:"groep",
  mess:2, bite:1, destruct:1, difficulty:3, space:2, hours:[0.25,0.5], beginner:3, cost:2, talk:0, song:1,
  slender:false, bold:1, ground:1, vsBirds:1, hormonal:2,
  tag:"Levend schilderij — maar gevoelig.",
  pros:["Spectaculaire kleuren","Zeer stil","Weinig interactie nodig"],
  cons:["Gevoelig voor kou en stress","Niet tam","Minder geschikt voor beginners dan andere vinken"],
  risks:["Luchtzakmijt","Gevoelig voor temperatuurschommelingen","Stress bij ruien"],
  pairNote:"Minimaal een paar, liefst een groepje.",
  sexNote:"Mannen zijn feller gekleurd. Voor welzijn maakt geslacht weinig uit; gemengd = kweekrisico.",
  mut:[["Roodkop (wildkleur)",{}],["Zwartkop",{head:"#222"}],["Witborst",{chest:"#f2f0ea"}],["Blauw",{wing:"#4a8ac8",body:"#e0e6ea"}]],
  day:"Een warme, tochtvrije vlucht met veel licht. Jij geniet van de kleuren; zij hebben elkaar.",
  c:{body:"#f2cf3a",chest:"#7b3fa0",head:"#c0392b",cheek:"#2a2a2a",wing:"#3f9a3c",tail:"#2d2d2d",beak:"#e8b0a0"}, beak:"cone", tail:"medium",
  src:["lafeber"] },

{ id:"diamantduif", nl:"Diamantduif", sci:"Geopelia cuneata", cat:"Zang- en siervogels", cm:"19–21 cm",
  size:2, life:[8,14], noise:1, noiseNote:"Zacht koeren; mannen ook ‘s ochtends, maar nooit schel.",
  handsOn:2, bond:2, clown:1, intel:1, train:1, activity:1, flight:3, social:4, pair:"paar",
  mess:2, bite:1, destruct:1, difficulty:1, space:2, hours:[0.25,1], beginner:5, cost:1, talk:0, song:2,
  slender:true, bold:1, ground:4, vsBirds:1, hormonal:2,
  tag:"Zacht koerende rust in huis.",
  pros:["Zeer rustig en zacht","Kan redelijk mak worden","Makkelijk te verzorgen","Gaat goed samen met vinken in een volière"],
  cons:["Weinig speels of interactief","Scharrelt veel op de grond","Paniekvlieger bij schrik"],
  risks:["Verwondingen bij paniekvluchten","Eileg-problemen"],
  pairNote:"Houd ze als paar. Twee mannen kunnen botsen.",
  sexNote:"Mannen hebben een bredere rode oogring en koeren meer. Een paar zal broeden (2 eieren); eieren vervangen door dummy’s kan.",
  mut:[["Wildkleur",{}],["Bont",{wing:"#e8e6e0"}],["Rood/cinnamon",{body:"#c9a48a",head:"#c9a48a",wing:"#b08a70",tail:"#b08a70"}]],
  day:"Een vlucht met veel bodemoppervlak, zand en zaad. Rustig gekoer op de achtergrond van je dag.",
  c:{body:"#c4cad0",head:"#aab2ba",wing:"#8f969c",tail:"#8f969c",beak:"#4a4a4a",eye:"#e2512f"}, beak:"thin", tail:"long",
  src:["lafeber"] },

// ---------------- Parkieten ----------------
{ id:"grasparkiet", nl:"Grasparkiet", sci:"Melopsittacus undulatus", cat:"Parkieten", cm:"18 cm",
  size:1, life:[7,12], noise:2, noiseNote:"Vrolijk gekwetter en babbelen; zelden echt hard.",
  handsOn:3, bond:3, clown:3, intel:3, train:4, activity:4, flight:4, social:5, pair:"paar",
  mess:2, bite:2, destruct:2, difficulty:1, space:2, hours:[0.5,1.5], beginner:5, cost:1, talk:4, song:3,
  slender:true, bold:2, ground:2, vsBirds:2, hormonal:3,
  tag:"Klein, slim en onderschat.",
  pros:["Zeer geschikt voor beginners","Goed trainbaar (target, step-up, trucs)","Mannen kunnen veel woordjes leren","Goede vlieger"],
  cons:["Hoort met een soortgenoot (LICG)","Tam worden kost geduld","Korter leven dan veel papegaaien"],
  risks:["Tumoren (relatief vaak)","Leg-nood bij poppen","Overgewicht bij zaad-only"],
  pairNote:"LICG adviseert grasparkieten niet alleen te houden. Twee is de norm; ze kunnen dan nog steeds tam worden.",
  sexNote:"Man: blauwe/paarse cere (neus). Pop: bruin/beige cere. Poppen kunnen chronisch eieren leggen en wat feller bijten.",
  mut:[["Groen (wildkleur)",{}],["Blauw",{body:"#6ab7e8",head:"#f4f4f4",tail:"#2f4f8f",wing:"#3a4a5a"}],["Lutino",{body:"#f6e45a",head:"#f8ec80",wing:"#efe08a",tail:"#efe8b0",cheek:"#f2f0f0"}],["Albino",{body:"#f6f6f4",head:"#fafafa",wing:"#ecebe8",tail:"#ecebe8",cheek:"#f6f6f4"}],["Violet",{body:"#8a78c8",head:"#f4f4f4",tail:"#4a3f8a"}]],
  day:"Twee vogels die elkaar bezighouden terwijl jij werkt; ’s avonds een uurtje vrij vliegen en een korte target-training met trosgierst.",
  c:{body:"#7ccf3a",head:"#f3e04c",wing:"#4b5a2a",tail:"#2f4f8f",cheek:"#2f4fbf",beak:"#c9a24b"}, beak:"hook", tail:"long",
  src:["licg_gras","lafeber"] },

{ id:"engelsegras", nl:"Engelse grasparkiet", sci:"Melopsittacus undulatus (tentoonstellingstype)", cat:"Parkieten", cm:"21–25 cm",
  size:2, life:[6,9], noise:2, noiseNote:"Rustiger dan de gewone grasparkiet.",
  handsOn:3, bond:3, clown:2, intel:3, train:3, activity:2, flight:2, social:4, pair:"paar",
  mess:2, bite:1, destruct:1, difficulty:2, space:2, hours:[0.5,1.5], beginner:4, cost:2, talk:3, song:2,
  slender:false, bold:1, ground:2, vsBirds:1, hormonal:3,
  tag:"De rustige, pluizige neef — gefokt voor de show.",
  pros:["Vaak rustig en makkelijk te hanteren","Groter en pluiziger","Zacht van geluid"],
  cons:["Kortere levensduur","Minder goede vlieger","Fok op uiterlijk geeft meer gezondheidsrisico’s"],
  risks:["Overgewicht","Tumoren","Veerproblemen (‘feather duster’ bij sommige lijnen)"],
  pairNote:"Net als de gewone grasparkiet: liefst met een soortgenoot.",
  sexNote:"Zelfde cere-kenmerken als de grasparkiet; poppen kunnen veel eieren leggen.",
  mut:[["Groen",{}],["Blauw",{body:"#6ab7e8",head:"#f4f4f4",tail:"#2f4f8f",wing:"#3a4a5a"}],["Grijs",{body:"#9aa0a6",head:"#f4f4f4",tail:"#5a5f66"}]],
  day:"Een ruime kooi met veel klimmogelijkheden en dagelijks rustig vliegen; houd het gewicht in de gaten.",
  c:{body:"#7ccf3a",head:"#f3e04c",wing:"#4b5a2a",tail:"#2f4f8f",cheek:"#2f4fbf",beak:"#c9a24b"}, beak:"hook", tail:"medium", bigHead:true,
  src:["licg_gras","lafeber"] },

{ id:"valkparkiet", nl:"Valkparkiet", sci:"Nymphicus hollandicus", cat:"Parkieten", cm:"30–34 cm",
  size:2, life:[15,25], noise:3, noiseNote:"Fluiten en een schelle contactroep (LICG) als je de kamer uitloopt; geen langdurig gekrijs.",
  handsOn:5, bond:5, clown:3, intel:3, train:4, activity:3, flight:5, social:4, pair:"flex",
  mess:4, bite:2, destruct:2, difficulty:2, space:3, hours:[1,3], beginner:5, cost:2, talk:2, song:3,
  slender:true, bold:1, ground:2, vsBirds:1, hormonal:3,
  tag:"Aanhankelijke fluiter met kuif en vliegtalent.",
  pros:["Zeer aanhankelijk en knuffelbaar","Prachtige, snelle vlieger","Vaak zacht in de omgang, bijt weinig","Leert melodietjes fluiten"],
  cons:["Veel veerstof (poederdons)","Schelle roep bij alleen zijn","Schrikt ’s nachts soms (nachtpaniek)"],
  risks:["Chronische eileg bij poppen","Nachtpaniek → verwondingen (nachtlampje helpt)","Stof kan allergie verergeren"],
  pairNote:"Eén kan, als jij veel thuis bent en dagelijks uren tijd hebt. Ben je vaak lang weg: neem er twee.",
  sexNote:"Bij wildkleur kleuren mannen een felgele kop; bij veel mutaties is DNA nodig. Mannen fluiten meer; poppen kunnen chronisch leggen.",
  mut:[["Grijs (wildkleur)",{}],["Lutino",{body:"#f6efc8",head:"#f6e27a",crest:"#f6e27a",wing:"#f2e8c0",tail:"#efe6c0"}],["Parel",{wing:"#c9b98a",body:"#a8a49a"}],["Bont",{body:"#e8e4dc",wing:"#9a9a9a"}],["Witkop (whiteface)",{head:"#f2f2f2",crest:"#e8e8e8",cheek:"#f2f2f2"}],["Cinnamon",{body:"#a8927a",wing:"#9a8670",tail:"#8a7660"}]],
  day:"’s Ochtends een korte trainingssessie, uren vrij vliegen en op schouders hangen als je thuis bent, ’s avonds knuffelen op de bank en 10–12 uur donker slapen met een nachtlampje.",
  c:{body:"#9a9a9a",head:"#f1d24a",crest:"#f1d24a",cheek:"#e8813a",wing:"#878787",tail:"#6e6e6e",beak:"#a49a90"}, beak:"hook", tail:"long", crest:"tuft",
  src:["licg_valk","nbvv","lafeber","young"] },

{ id:"bourke", nl:"Bourke’s parkiet", sci:"Neopsephotus bourkii", cat:"Parkieten", cm:"19 cm",
  size:1, life:[10,15], noise:1, noiseNote:"Zeer zacht, vooral actief in schemer.",
  handsOn:2, bond:2, clown:1, intel:2, train:2, activity:2, flight:3, social:4, pair:"paar",
  mess:2, bite:1, destruct:1, difficulty:1, space:2, hours:[0.25,1], beginner:5, cost:2, talk:0, song:2,
  slender:true, bold:1, ground:3, vsBirds:1, hormonal:2,
  tag:"De stilste parkiet: zachtaardig en rustig.",
  pros:["Een van de stilste parkieten","Vreedzaam, ook met vinken","Makkelijk en sterk","Mooie roze tinten"],
  cons:["Weinig speels","Meestal niet echt knuffeltam","Actief in de schemer"],
  risks:["Wormen bij grondcontact in buitenvolière","Overgewicht"],
  pairNote:"Houd ze als paar; ze zijn sociaal maar niet mensgericht.",
  sexNote:"Mannen hebben een blauw voorhoofdje. Gemengde paren broeden makkelijk.",
  mut:[["Wildkleur",{}],["Roze (rosa)",{body:"#f2a6c0",head:"#f4b8c8",wing:"#e8a0b8",tail:"#e8b0c4"}],["Opaline roze",{body:"#ef8fb0",wing:"#f2b0c8"}]],
  day:"Een paar in een brede kooi of kamervolière; ’s avonds rustig scharrelen en vliegen. Ideaal voor een rustig huis.",
  c:{body:"#e7a6b8",head:"#c99aa0",wing:"#8f7a6a",tail:"#6a7fa8",beak:"#8b8b8b"}, beak:"hook", tail:"long",
  src:["lafeber"] },

{ id:"catharina", nl:"Catharinaparkiet", sci:"Bolborhynchus lineola", cat:"Parkieten", cm:"16 cm",
  size:1, life:[10,15], noise:1, noiseNote:"Zacht gekwetter; een van de stilste kromsnavels.",
  handsOn:4, bond:3, clown:2, intel:3, train:3, activity:2, flight:2, social:4, pair:"flex",
  mess:2, bite:1, destruct:1, difficulty:2, space:2, hours:[0.5,2], beginner:4, cost:2, talk:2, song:2,
  slender:false, bold:1, ground:2, vsBirds:1, hormonal:2,
  tag:"Rustige klimmer die graag in je hand zit.",
  pros:["Heel stil","Kalm en vaak goed handtam","Weinig rommel en sloopgedrag"],
  cons:["Meer klimmer dan vlieger","Minder ‘clownesk’","Kan schrikachtig zijn"],
  risks:["Gevoelig voor tocht","Overgewicht"],
  pairNote:"Een paar is ideaal; één kan met dagelijks gezelschap van jou.",
  sexNote:"Mannen hebben vaak meer zwarte tekening; betrouwbaar alleen via DNA.",
  mut:[["Groen",{}],["Turquoise/blauw",{body:"#5ab0b8",head:"#5ab0b8",wing:"#2f6f78",tail:"#3f8a90"}],["Lutino",{body:"#f2e47a",head:"#f2e47a",wing:"#e8d86a",tail:"#e8d86a"}],["Cobalt",{body:"#3f7fc0",head:"#3f7fc0",wing:"#2a4f80",tail:"#2f5f9a"}]],
  day:"Klimmen, foerageren en rustig op je hand of schouder zitten; een kort vlieg- en klimmoment per dag.",
  c:{body:"#5aa04a",head:"#5aa04a",wing:"#2f5f2f",tail:"#3e7a35",beak:"#e8dcc0"}, beak:"hook", tail:"short",
  src:["lafeber"] },

{ id:"kakariki", nl:"Roodvoorhoofdkakariki", sci:"Cyanoramphus novaezelandiae", cat:"Parkieten", cm:"27–30 cm",
  size:2, life:[8,15], noise:3, noiseNote:"Kwetterend ‘gegiechel’, kan bij opwinding hard worden.",
  handsOn:2, bond:3, clown:5, intel:4, train:3, activity:5, flight:3, social:4, pair:"paar",
  mess:4, bite:2, destruct:3, difficulty:3, space:3, hours:[1,2], beginner:2, cost:2, talk:1, song:1,
  slender:true, bold:3, ground:5, vsBirds:3, hormonal:3,
  tag:"Hyperactieve scharrelaar: nooit saai, nooit stil.",
  pros:["Extreem speels en grappig","Nieuwsgierig","Graaft, krabt en onderzoekt alles"],
  cons:["Hyperactief, weinig knuffelaar","Rommelt en spat","Scharrelt veel op de grond (risico bij andere dieren)"],
  risks:["Gevoelig bij verkeerde voeding","Verwondingen door drukte","Kan andere vogels lastigvallen"],
  pairNote:"Bij voorkeur als paar of groepje; erg sociaal.",
  sexNote:"Mannen zijn iets groter met bredere kop; DNA is betrouwbaarder.",
  mut:[["Groen (wildkleur)",{}],["Bont",{body:"#c8e07a",wing:"#e8e4a0"}],["Cinnamon",{body:"#a8c070",wing:"#8aa060"}]],
  day:"Een brede volière met graafbak, schorsen en zaadbollen; dagelijks scharrelen in een vogelveilige kamer onder toezicht.",
  c:{body:"#49a83c",head:"#49a83c",cap:"#d42a2a",wing:"#2f8a3a",tail:"#3c8f32",beak:"#8aa0b8"}, beak:"hook", tail:"long",
  src:["lafeber","wpt"] },

{ id:"halsband", nl:"Halsbandparkiet", sci:"Psittacula krameri", cat:"Parkieten", cm:"38–42 cm",
  size:3, life:[20,30], noise:4, noiseNote:"Scherpe, luide roep, ’s ochtends en ’s avonds; duidelijk hoorbaar bij buren.",
  handsOn:2, bond:3, clown:3, intel:4, train:4, activity:4, flight:5, social:4, pair:"flex",
  mess:3, bite:3, destruct:3, difficulty:4, space:4, hours:[1,3], beginner:2, cost:3, talk:4, song:1,
  slender:true, bold:3, ground:1, vsBirds:3, hormonal:4,
  tag:"Elegante topvlieger met een eigen willetje.",
  pros:["Prachtige, slanke vlieger","Intelligent; kan goed praten","Zelfstandiger dan veel papegaaien"],
  cons:["Luid","‘Bluffase’ in de puberteit: bijterig en schuw","Geen knuffelvogel; band moet onderhouden worden"],
  risks:["Gedragsproblemen bij inconsequente omgang","Ontsnapping: komt in NL voor als invasieve exoot"],
  pairNote:"Een goed gesocialiseerde vogel kan alleen met veel tijd; anders een paar in een grote volière.",
  sexNote:"Volwassen mannen (±3 jaar) krijgen een halsband; vóór die tijd DNA. Rond 1–2 jaar komt de bluffase bij beide geslachten voor.",
  legal:"Verwilderd in Nederland als invasieve exoot (Sovon 2025). Nooit loslaten of laten ontsnappen. Controleer of de soort inmiddels op de EU-Unielijst staat (IPLO).",
  mut:[["Groen",{}],["Blauw",{body:"#7ab8d8",head:"#7ab8d8",wing:"#4a88b8",tail:"#4a88b8"}],["Lutino",{body:"#f2e04a",head:"#f2e04a",wing:"#e8d43a",tail:"#e8d43a",ring:"#f2b8c8"}],["Grijs",{body:"#a0a8a8",head:"#a0a8a8",wing:"#7a8282",tail:"#6a7272"}]],
  day:"Een grote kooi of volière, dagelijks lange vliegsessies en consequente, korte trainingen om de band te houden.",
  c:{body:"#7bc96b",head:"#7bc96b",ring:"#2a2a2a",wing:"#5aaf55",tail:"#4f9f9a",beak:"#c0272d"}, beak:"hook", tail:"verylong",
  src:["sovon","iplo","eu2025","wpt","young"] },

{ id:"turquoisine", nl:"Turquoisine", sci:"Neophema pulchella", cat:"Parkieten", cm:"20 cm",
  size:1, life:[10,15], noise:1, noiseNote:"Zacht gefluit en getjilp.",
  handsOn:1, bond:1, clown:1, intel:2, train:1, activity:2, flight:4, social:4, pair:"paar",
  mess:2, bite:1, destruct:1, difficulty:2, space:3, hours:[0.25,0.5], beginner:4, cost:2, talk:0, song:2,
  slender:true, bold:1, ground:3, vsBirds:1, hormonal:2,
  tag:"Stil juweeltje voor de volière.",
  pros:["Heel stil","Prachtige kleuren","Vreedzaam"],
  cons:["Niet handtam","Volièrevogel: heeft vlieglengte nodig","Schrikachtig"],
  risks:["Wormen in buitenvolière","Paniekvluchten"],
  pairNote:"Houd ze als paar in een volière.",
  sexNote:"Mannen hebben rode schoudervlekken. Een paar zal willen broeden.",
  mut:[["Wildkleur",{}],["Geel",{body:"#f6e05a",wing:"#f2d84a",head:"#f2d84a",cheek:"#f2e080"}],["Roodbuik",{body:"#e86a3a"}]],
  day:"Een lange (buiten)volière met vliegruimte. Jij kijkt; zij vliegen.",
  c:{body:"#f2d33a",head:"#3a8a3a",cheek:"#2a8fd0",wing:"#3a7d3a",tail:"#3a7d3a",beak:"#3a3a3a",chest:"#f2d33a"}, beak:"hook", tail:"long", shoulder:"#d23a2a",
  src:["lafeber"] },

{ id:"splendide", nl:"Splendide parkiet", sci:"Neophema splendida", cat:"Parkieten", cm:"19–20 cm",
  size:1, life:[10,15], noise:1, noiseNote:"Zacht en melodieus.",
  handsOn:2, bond:2, clown:1, intel:2, train:2, activity:2, flight:4, social:4, pair:"paar",
  mess:2, bite:1, destruct:1, difficulty:2, space:3, hours:[0.25,1], beginner:4, cost:2, talk:0, song:2,
  slender:true, bold:1, ground:3, vsBirds:1, hormonal:2,
  tag:"Rustige kleurenbom, zelden lastig.",
  pros:["Stil en zachtaardig","Felle kleuren","Kan redelijk mak worden"],
  cons:["Weinig interactief","Heeft vliegruimte nodig"],
  risks:["Wormen","Gevoelig voor vocht/kou"],
  pairNote:"Als paar houden.",
  sexNote:"Mannen hebben een rode borst. Een gemengd paar wil broeden.",
  mut:[["Wildkleur",{}],["Blauw",{body:"#e8f0f2",chest:"#e8f0f2",wing:"#4aa0b8",tail:"#4aa0b8"}],["Witborst",{chest:"#f4f4f4"}]],
  day:"Een kamervolière met lengte; vreedzaam gezelschap dat weinig van je vraagt.",
  c:{body:"#f2d33a",chest:"#d92f2f",head:"#2b74c9",wing:"#3a8a3a",tail:"#3a8a3a",beak:"#3a3a3a"}, beak:"hook", tail:"long",
  src:["lafeber"] },

{ id:"rosella", nl:"Prachtrosella", sci:"Platycercus eximius", cat:"Parkieten", cm:"30 cm",
  size:2, life:[15,25], noise:3, noiseNote:"Melodieus fluiten, maar ook luide contactroepen.",
  handsOn:1, bond:2, clown:2, intel:3, train:2, activity:4, flight:5, social:3, pair:"paar",
  mess:3, bite:3, destruct:2, difficulty:3, space:4, hours:[0.25,1], beginner:3, cost:2, talk:1, song:3,
  slender:true, bold:3, ground:3, vsBirds:4, hormonal:3,
  tag:"Spectaculaire volièrevogel — geen schootvogel.",
  pros:["Prachtige kleuren","Fluit mooi","Weinig behoefte aan menselijke aandacht"],
  cons:["Heeft echt een (buiten)volière nodig","Agressief naar andere soorten","Zelden handtam"],
  risks:["Wormen in buitenvolière","Agressie in gemengde volière"],
  pairNote:"Als paar, niet met andere parkieten samen.",
  sexNote:"Mannen zijn iets feller; DNA voor zekerheid. Paren kunnen in broedtijd fel zijn.",
  mut:[["Wildkleur",{}],["Rood/rubino",{body:"#e8604a",wing:"#f2b8a0"}],["Opaline",{wing:"#2a2a2a"}]],
  day:"Een lange buitenvolière met nachthok; dagelijks vers voer en een badje.",
  c:{body:"#f2d33a",chest:"#d42a2a",head:"#d42a2a",cheek:"#f4f4f4",wing:"#2a2a2a",tail:"#2f66c4",beak:"#e8e0d0"}, beak:"hook", tail:"long", scallop:"#e8c43a",
  src:["lafeber","wpt"] },

// ---------------- Kleine papegaaien ----------------
{ id:"forpus", nl:"Forpus (muspapegaaitje)", sci:"Forpus coelestis", cat:"Kleine papegaaien", cm:"12–13 cm",
  size:1, life:[15,25], noise:2, noiseNote:"Zacht getjilp; een van de stilste papegaaien.",
  handsOn:3, bond:4, clown:3, intel:3, train:3, activity:4, flight:3, social:3, pair:"flex",
  mess:3, bite:3, destruct:3, difficulty:3, space:2, hours:[1,2], beginner:3, cost:2, talk:1, song:1,
  slender:false, bold:5, ground:2, vsBirds:5, hormonal:3,
  tag:"Een grote papegaai in een klein pakketje.",
  pros:["Stil — appartementvriendelijk","Veel karakter","Klein, dus minder ruimte nodig","Kan sterke band met eigenaar vormen"],
  cons:["Kan territoriaal en bijterig zijn","Zeer gevaarlijk voor andere vogels (bijt pootjes)","Band verwatert zonder dagelijkse omgang"],
  risks:["Verwondingen bij of door andere vogels","Eileg bij poppen"],
  pairNote:"Eén geeft de sterkste band met jou; een paar is soms minder tam en kan onderling fel zijn.",
  sexNote:"Mannen hebben blauw op vleugel en rug. Poppen kunnen iets territorialer zijn, maar individuele verschillen domineren.",
  mut:[["Groen",{}],["Blauw",{body:"#7ab8d8",head:"#7ab8d8",wing:"#3f6fb0",tail:"#6aa0c8"}],["Geel (Amerikaans)",{body:"#f2e05a",head:"#f2e05a",wing:"#e8d44a",tail:"#e8d44a"}],["Grijs",{body:"#a8b0b0",head:"#a8b0b0",wing:"#6a7a8a",tail:"#8a9090"}]],
  day:"Korte, frequente sessies: hand-taming, wat trucjes, vrij in een kamer. Veel foerageerspeelgoed als je weg bent.",
  c:{body:"#8fd37a",head:"#8fd37a",wing:"#3a7fd8",tail:"#7fc06a",beak:"#e8c8b0"}, beak:"hook", tail:"short",
  src:["lafeber","wpt","young"] },

{ id:"perzikkop", nl:"Perzikkopagapornis", sci:"Agapornis roseicollis", cat:"Kleine papegaaien", cm:"15–18 cm",
  size:1, life:[10,20], noise:3, noiseNote:"Schel en frequent getjilp; scherper dan je verwacht van zo’n kleine vogel.",
  handsOn:3, bond:4, clown:4, intel:3, train:3, activity:4, flight:3, social:4, pair:"flex",
  mess:4, bite:4, destruct:4, difficulty:3, space:2, hours:[1,2], beginner:3, cost:2, talk:0, song:0,
  slender:false, bold:5, ground:2, vsBirds:5, hormonal:4,
  tag:"Klein, brutaal en verslavend leuk.",
  pros:["Speels en eigenwijs","Kan zeer tam worden (zeker één vogel)","Klein formaat"],
  cons:["Bijt flink","Schel geluid","Versnippert papier en hout","Agressief naar andere soorten"],
  risks:["Chronische eileg bij poppen","Verwondingen bij andere vogels"],
  pairNote:"‘Lovebird’ betekent níet dat ze een partner nodig hebben om gelukkig te zijn; één vogel met veel aandacht is vaak tammer. Een paar is zelfstandiger.",
  sexNote:"Uiterlijk niet te onderscheiden: DNA. Poppen versnipperen nestmateriaal en leggen soms veel eieren.",
  mut:[["Wildkleur",{}],["Lutino",{body:"#f6e45a",head:"#f29a8a",wing:"#f2e05a",tail:"#f2e870"}],["Blauw (aqua)",{body:"#7ec8b8",head:"#f2e8d8",wing:"#5aa898",tail:"#5a9fc0"}],["Opaline",{head:"#f0807a",body:"#7ccc4a"}]],
  day:"Dagelijks spelen, hand-time en vrij in een kamer; papier om te versnipperen en veel afwisseling in speelgoed.",
  c:{body:"#7ccc4a",head:"#ef8a7a",cheek:"#ef8a7a",wing:"#4f9b3a",tail:"#3b6fc0",beak:"#e8d8a0"}, beak:"hook", tail:"short",
  src:["lafeber","wpt"] },

{ id:"oogring", nl:"Oogring-agapornis (zwartmasker/Fischers)", sci:"Agapornis personatus / A. fischeri", cat:"Kleine papegaaien", cm:"14–15 cm",
  size:1, life:[10,20], noise:3, noiseNote:"Schel en veel; in een groep flink aanwezig.",
  handsOn:2, bond:3, clown:4, intel:3, train:2, activity:4, flight:3, social:5, pair:"paar",
  mess:4, bite:4, destruct:4, difficulty:3, space:2, hours:[0.5,1.5], beginner:3, cost:2, talk:0, song:0,
  slender:false, bold:4, ground:2, vsBirds:5, hormonal:4,
  tag:"Felgekleurd koppeltje met pit.",
  pros:["Prachtige kleuren","Speels","Als paar zelfstandig"],
  cons:["Bijterig","Schel","Agressief naar andere soorten"],
  risks:["Eileg","Verwondingen in gemengde groepen"],
  pairNote:"Meestal als paar gehouden; minder mensgericht dan een enkele perzikkop.",
  sexNote:"DNA nodig. Twee poppen kunnen ook samen (wel kans op onbevruchte eieren).",
  mut:[["Zwartmasker (wild)",{}],["Blauw",{body:"#6ab0d8",chest:"#f2f2f2",wing:"#4a90c0",tail:"#4a90c0"}],["Fischers",{head:"#e9773a",cap:"#e9773a"}]],
  day:"Een paar met veel speelgoed in een ruime kooi, vrije tijd in een kamer; jij bent vooral entertainment, geen partner.",
  c:{body:"#7ccc4a",chest:"#f2d33a",head:"#2a2a2a",wing:"#4f9b3a",tail:"#3f8a3a",beak:"#d83a2a",eye:"#f4f4f4"}, beak:"hook", tail:"short",
  src:["lafeber","wpt"] },

{ id:"pyrrhura", nl:"Groenwangparkiet (Pyrrhura)", sci:"Pyrrhura molinae", cat:"Kleine papegaaien", cm:"25–26 cm",
  size:2, life:[20,30], noise:3, noiseNote:"Korte, scherpe roepjes bij opwinding; rustiger dan grote conures en de meeste andere kleine papegaaien van dit karakterniveau.",
  handsOn:5, bond:5, clown:5, intel:4, train:5, activity:5, flight:4, social:4, pair:"flex",
  mess:4, bite:3, destruct:4, difficulty:3, space:3, hours:[2,4], beginner:4, cost:3, talk:1, song:0,
  slender:true, bold:4, ground:2, vsBirds:3, hormonal:3,
  tag:"Clownesk knuffelmonster met een slank silhouet.",
  pros:["Extreem speels en aanhankelijk","Uitstekend trainbaar (target, recall, trucs, tuigje)","Goede, wendbare vlieger","Relatief stil voor een papegaai met dit karakter"],
  cons:["Kan bijten (vooral in puberteit/hormonaal)","Sloopt en rommelt","Heeft dagelijks uren aandacht nodig","Brutaal richting andere dieren"],
  risks:["Gedragsproblemen bij verveling (o.a. plukken)","Hormonaal gedrag bij te veel aaien over rug/onder vleugels","Verwondingen door andere huisdieren"],
  pairNote:"Eén geeft de meest mensgerichte vogel, maar vraagt dagelijks uren. Twee blijven tam als je beide traint, en zijn beter bestand tegen lange werkdagen.",
  sexNote:"Uiterlijk niet te onderscheiden: DNA. Poppen kunnen eieren leggen; mannen en poppen kunnen beide hormonaal territoriaal worden.",
  mut:[["Wildkleur",{}],["Yellow-sided",{chest:"#e8c53a",belly:"#c8442f"}],["Pineapple",{body:"#9fd06a",chest:"#f2c23a",head:"#a07a5a",belly:"#e25a3a",tail:"#b8604a",wing:"#8fc85a"}],["Cinnamon",{body:"#86c46e",head:"#8a6d5a",wing:"#76b45e",tail:"#a85a4a"}],["Turquoise",{body:"#3fa89a",wing:"#2f8a80",head:"#3a3a3a",belly:"#8a9aa0",tail:"#6a8a8a",cheek:"#3f9a90"}],["Turquoise pineapple",{body:"#8fd0c4",chest:"#e8e2b0",head:"#a09a8a",belly:"#c8c8b8",tail:"#a0b8b0",wing:"#7fc0b4",cheek:"#8fd0c4"}]],
  day:"Een korte trainingssessie ’s ochtends, foerageerspeelgoed als je werkt, uren vrij vliegen en ‘spelen’ als je thuis bent, ’s avonds terug in de kooi voor 10–12 uur slaap.",
  c:{body:"#4f9a3a",chest:"#a29270",belly:"#a7322a",head:"#4a3d36",cheek:"#3f8f3a",wing:"#3a7f3a",tail:"#8a2a2a",beak:"#2a2a2a",eye:"#f4f4f4"}, beak:"hook", tail:"long", scale:true,
  src:["lafeber","wpt","young"] },

{ id:"zonparkiet", nl:"Zonparkiet", sci:"Aratinga solstitialis", cat:"Kleine papegaaien", cm:"30 cm",
  size:2, life:[20,30], noise:5, noiseNote:"Zeer luide, doordringende krijs; een van de luidste kleinere papegaaien.",
  handsOn:5, bond:5, clown:5, intel:4, train:4, activity:5, flight:4, social:4, pair:"flex",
  mess:4, bite:3, destruct:4, difficulty:4, space:3, hours:[2,4], beginner:2, cost:3, talk:1, song:0,
  slender:true, bold:3, ground:2, vsBirds:3, hormonal:3,
  tag:"Goudgeel, knuffelig — en oorverdovend.",
  pros:["Spectaculair goud-oranje","Zeer aanhankelijk en speels","Trainbaar"],
  cons:["Extreem luid","Vraagt veel aandacht","Niet geschikt voor appartementen"],
  risks:["Schreeuwgedrag bij verveling","Klachten van buren"],
  pairNote:"Eén met heel veel aandacht, of twee (dubbel geluid).",
  sexNote:"DNA nodig. Geen betrouwbaar karakterverschil tussen geslachten.",
  mut:[["Wildkleur",{}]],
  day:"Veel spelen, trainen en vrij vliegen; plan rustmomenten en geluidsbewuste routines.",
  c:{body:"#f6b32a",chest:"#f39a23",head:"#f39a23",cheek:"#f07a1f",wing:"#4a9a3a",tail:"#4a8a3a",beak:"#222",eye:"#f4f4f4"}, beak:"hook", tail:"long", primaries:"#2a66b8",
  src:["lafeber","wpt"] },

{ id:"monnik", nl:"Monniksparkiet", sci:"Myiopsitta monachus", cat:"Kleine papegaaien", cm:"29 cm",
  size:2, life:[20,30], noise:4, noiseNote:"Luid en veel ‘gebabbel’; kan schreeuwen.",
  handsOn:4, bond:4, clown:4, intel:4, train:4, activity:4, flight:3, social:4, pair:"flex",
  mess:4, bite:3, destruct:4, difficulty:3, space:3, hours:[2,4], beginner:3, cost:3, talk:4, song:0,
  slender:true, bold:4, ground:2, vsBirds:3, hormonal:3,
  tag:"Prater en bouwer met een groot karakter.",
  pros:["Kan goed praten","Sociaal en speels","Sterk en nieuwsgierig"],
  cons:["Luid","Bouwt nesten en sloopt","Kan territoriaal rond de kooi zijn"],
  risks:["Ontsnapping: vestigt zich in NL in het wild","Territoriaal gedrag"],
  pairNote:"Eén met veel aandacht, of meerdere in een ruime volière.",
  sexNote:"DNA nodig. Beide geslachten bouwen nesten.",
  legal:"In meerdere landen gereguleerd of verboden. In NL verwilderd; mogelijk toekomstige plaatsing op de EU-Unielijst (Sovon 2025). Controleer actuele regels.",
  mut:[["Groen",{}],["Blauw",{body:"#7ab8d8",wing:"#3f6fb0",tail:"#6aa0c8"}],["Lutino",{body:"#f2e05a",wing:"#e8d44a",tail:"#e8d44a"}]],
  day:"Praten, trainen, nestmateriaal sjouwen en veel spelen; een stevige kooi met takken om te bouwen.",
  c:{body:"#7cbf5a",chest:"#c9ccc4",head:"#c9ccc4",wing:"#5aaa4a",tail:"#6aa84a",beak:"#e7c9a6"}, beak:"hook", tail:"long", primaries:"#3a6fb0",
  src:["sovon","iplo","wpt"] },

// ---------------- Middelgrote papegaaien ----------------
{ id:"pionus", nl:"Pionus (o.a. Maximiliaans muspapegaai)", sci:"Pionus maximiliani e.a.", cat:"Middelgrote papegaaien", cm:"28–30 cm",
  size:3, life:[25,40], noise:3, noiseNote:"Matig; kan roepen, maar rustiger dan amazones en conures.",
  handsOn:3, bond:3, clown:2, intel:4, train:3, activity:2, flight:3, social:3, pair:"flex",
  mess:3, bite:2, destruct:3, difficulty:3, space:3, hours:[2,3], beginner:3, cost:4, talk:2, song:0,
  slender:false, bold:2, ground:2, vsBirds:2, hormonal:3,
  tag:"De rustige, waardige papegaai.",
  pros:["Relatief rustig en kalm","Minder veeleisend dan veel papegaaien","Vaak mild in de omgang"],
  cons:["Minder clownesk","Niet de typische knuffelaar","Hijgt/‘sniffelt’ bij stress, wat vaak voor ziekte wordt aangezien"],
  risks:["Aspergillose (luchtwegschimmel)","Vitamine A-tekort bij zaad-only","Overgewicht"],
  pairNote:"Eén kan goed met dagelijks gezelschap; ze zijn redelijk zelfstandig.",
  sexNote:"DNA nodig. Geen betrouwbaar karakterverschil.",
  mut:[["Wildkleur",{}]],
  day:"Een rustige routine: foerageren, klimmen, een uurtje vrij en samen chillen op een stok bij de bank.",
  c:{body:"#4a7a4a",chest:"#6a5a9a",head:"#3a5a8a",wing:"#3a6a3a",tail:"#3a6a3a",beak:"#e8d8c0",eye:"#e8e0d0"}, beak:"hook", tail:"short", vent:"#c43a3a",
  src:["lafeber","wpt","young"] },

{ id:"caique", nl:"Zwartkopcaique", sci:"Pionites melanocephalus", cat:"Middelgrote papegaaien", cm:"23 cm",
  size:2, life:[25,40], noise:4, noiseNote:"Schelle, luide roepen en fluiten.",
  handsOn:4, bond:4, clown:5, intel:4, train:4, activity:5, flight:2, social:4, pair:"flex",
  mess:4, bite:4, destruct:4, difficulty:4, space:3, hours:[2,4], beginner:2, cost:4, talk:1, song:0,
  slender:false, bold:5, ground:4, vsBirds:4, hormonal:3,
  tag:"Hyperactieve clown — dansend, rollend, bijtend.",
  pros:["Ongeëvenaard speels en grappig","Stoeit, rolt op de rug, ‘surft’ in je hand","Slim"],
  cons:["Bijt hard bij overprikkeling","Luid","Agressief naar andere dieren en vogels","Hopt meer dan dat hij vliegt"],
  risks:["Verwondingen van/aan andere dieren","Overprikkeling → bijten"],
  pairNote:"Eén met veel aandacht of twee caiques samen (niet met andere soorten).",
  sexNote:"DNA nodig. Geen betrouwbaar karakterverschil.",
  mut:[["Wildkleur",{}]],
  day:"Stoeien, trainen met duidelijke grenzen, speeltuin-stand en badderen; je leert overprikkeling herkennen.",
  c:{body:"#f4f1ea",chest:"#f4f1ea",head:"#1e1e1e",cheek:"#f2b13a",wing:"#3a8a3a",tail:"#3a8a3a",beak:"#222"}, beak:"hook", tail:"short",
  src:["lafeber","wpt"] },

{ id:"senegal", nl:"Senegalpapegaai", sci:"Poicephalus senegalus", cat:"Middelgrote papegaaien", cm:"23–25 cm",
  size:2, life:[25,40], noise:3, noiseNote:"Fluiten en piepen; geen extreem lawaai.",
  handsOn:3, bond:4, clown:3, intel:4, train:4, activity:3, flight:3, social:3, pair:"flex",
  mess:3, bite:3, destruct:3, difficulty:3, space:3, hours:[2,3], beginner:3, cost:3, talk:2, song:0,
  slender:false, bold:4, ground:2, vsBirds:4, hormonal:3,
  tag:"Compacte, slimme ‘één-persoonsvogel’.",
  pros:["Relatief stil voor een papegaai","Slim en trainbaar","Compact formaat"],
  cons:["Hecht zich vaak aan één persoon","Kan territoriaal en bijterig zijn","Jaloers gedrag"],
  risks:["Gedragsproblemen bij te weinig socialisatie","Overgewicht"],
  pairNote:"Vaak als één vogel gehouden; socialiseer met meerdere mensen.",
  sexNote:"DNA nodig (V-vormig borstschild bij poppen is een ruwe aanwijzing).",
  mut:[["Wildkleur",{}]],
  day:"Training, foerageren en vrij in een kamer; laat ook andere huisgenoten met hem werken.",
  c:{body:"#3a8a3a",chest:"#3a8a3a",belly:"#f2a23a",head:"#555a5f",wing:"#3a8a3a",tail:"#3a7a3a",beak:"#333",eye:"#f2e04a"}, beak:"hook", tail:"short",
  src:["lafeber","wpt"] },

{ id:"meyer", nl:"Meyers papegaai", sci:"Poicephalus meyeri", cat:"Middelgrote papegaaien", cm:"21–23 cm",
  size:2, life:[25,40], noise:2, noiseNote:"Een van de stilste papegaaien in zijn klasse.",
  handsOn:3, bond:3, clown:3, intel:4, train:4, activity:3, flight:3, social:3, pair:"flex",
  mess:3, bite:3, destruct:3, difficulty:3, space:3, hours:[1.5,3], beginner:3, cost:3, talk:2, song:0,
  slender:false, bold:3, ground:2, vsBirds:3, hormonal:3,
  tag:"Stil, slim en verrassend zelfstandig.",
  pros:["Stil","Kan zichzelf goed bezighouden","Slim en trainbaar"],
  cons:["Minder knuffelig","Kan bijten bij verkeerde omgang"],
  risks:["Overgewicht","Gedragsproblemen bij onderprikkeling"],
  pairNote:"Eén kan, mits dagelijks aandacht en verrijking.",
  sexNote:"DNA nodig.",
  mut:[["Wildkleur",{}]],
  day:"Foerageren, klimmen, een paar korte trainingen; tevreden naast je terwijl jij werkt.",
  c:{body:"#4fa4a8",chest:"#4fa4a8",head:"#6b5a45",cap:"#f2d03a",wing:"#6b5a45",tail:"#6b5a45",beak:"#333",eye:"#f2a23a"}, beak:"hook", tail:"short",
  src:["lafeber","wpt"] },

// ---------------- Grote papegaaien ----------------
{ id:"grijze", nl:"Grijze roodstaart", sci:"Psittacus erithacus", cat:"Grote papegaaien", cm:"33 cm",
  size:3, life:[40,60], noise:4, noiseNote:"Imiteert alles (ook alarmen); kan hard fluiten en schreeuwen.",
  handsOn:3, bond:5, clown:3, intel:5, train:5, activity:3, flight:3, social:4, pair:"flex",
  mess:4, bite:3, destruct:4, difficulty:5, space:4, hours:[3,5], beginner:1, cost:5, talk:5, song:0,
  slender:false, bold:3, ground:3, vsBirds:2, hormonal:3,
  tag:"Cognitief topniveau — en emotioneel kwetsbaar.",
  pros:["Uitzonderlijke intelligentie en spraak","Diepe band mogelijk","Rustig van uiterlijk"],
  cons:["Gevoelig voor stress en veranderingen","Plukgedrag bij onvoldoende verrijking","Leeft mogelijk langer dan jij"],
  risks:["Verenplukken","Calcium-/vitamine-D-tekort (o.a. UV-licht)","Aspergillose"],
  pairNote:"Vaak als één vogel; vereist dan zeer veel tijd en verrijking.",
  sexNote:"DNA nodig. Geen betrouwbaar karakterverschil.",
  legal:"CITES Bijlage I / EU-bijlage A: alleen met geldig EU-certificaat en gesloten ring kopen.",
  mut:[["Wildkleur",{}]],
  day:"Meerdere trainings- en foerageersessies, uren samen, UV-licht, en een voorspelbare routine.",
  c:{body:"#9aa0a5",chest:"#a8adb2",head:"#b8bdc2",cheek:"#eceeef",wing:"#868b90",tail:"#c22a2a",beak:"#222"}, beak:"bighook", tail:"short", scale:true,
  src:["cites","young","wpt","lafeber"] },

{ id:"amazone", nl:"Blauwvoorhoofdamazone", sci:"Amazona aestiva", cat:"Grote papegaaien", cm:"37 cm",
  size:4, life:[40,60], noise:5, noiseNote:"Zeer luid; ochtend- en avondsessies zijn normaal gedrag.",
  handsOn:4, bond:4, clown:4, intel:5, train:4, activity:3, flight:3, social:4, pair:"flex",
  mess:4, bite:4, destruct:4, difficulty:5, space:4, hours:[3,5], beginner:1, cost:5, talk:5, song:2,
  slender:false, bold:4, ground:2, vsBirds:3, hormonal:5,
  tag:"Theatrale prater met een groot hart en grote stem.",
  pros:["Uitbundig, speels en sociaal","Praat en zingt","Robuust"],
  cons:["Zeer luid","Hormonaal agressief in het voorjaar (vooral bij hechting aan één persoon)","Kan zwaar worden"],
  risks:["Overgewicht/vervetting","Hormonaal bijtgedrag"],
  pairNote:"Eén met zeer veel aandacht of een paar in een grote volière.",
  sexNote:"DNA nodig. Hormonale agressie bij beide geslachten mogelijk.",
  legal:"CITES Bijlage II: koop alleen met correcte papieren.",
  mut:[["Wildkleur",{}]],
  day:"Samen ‘zingen’, trainen, veel bewegen en gezond eten — en accepteren dat ochtend en avond luid zijn.",
  c:{body:"#4fa84a",head:"#f2d23a",cap:"#3a7fd0",wing:"#3fa040",tail:"#3f9a3a",beak:"#333"}, beak:"bighook", tail:"short", shoulder:"#d23a2a",
  src:["cites","young","wpt","lafeber"] },

{ id:"eclectus", nl:"Edelpapegaai (Eclectus)", sci:"Eclectus roratus s.l.", cat:"Grote papegaaien", cm:"35–42 cm",
  size:4, life:[30,50], noise:4, noiseNote:"Luide roep, maar meestal minder langdurig dan amazones.",
  handsOn:2, bond:3, clown:2, intel:4, train:4, activity:2, flight:3, social:3, pair:"flex",
  mess:4, bite:3, destruct:3, difficulty:5, space:4, hours:[2,4], beginner:1, cost:5, talk:4, song:0,
  slender:false, bold:3, ground:2, vsBirds:2, hormonal:4,
  tag:"Spectaculair en kalm — met een veeleisend dieet.",
  pros:["Prachtig (man groen, pop rood-blauw)","Vaak kalm en waarnemend","Kan goed praten"],
  cons:["Zeer specifieke voeding (veel vers, weinig vet/vitamine-supplementen)","Weinig knuffelig","Gevoelig voor stress"],
  risks:["Voedingsgerelateerde problemen (‘toe-tapping’, plukken)","Hormonaal gedrag"],
  pairNote:"Vaak één vogel; heeft een rustige, voorspelbare omgeving nodig.",
  sexNote:"Duidelijk dimorf: mannen groen, poppen rood/blauw. Persoonlijkheid verschilt vooral individueel; poppen kunnen in broedstemming territoriaal zijn.",
  mut:[["Man (groen)",{}],["Pop (rood/blauw)",{body:"#c8202a",head:"#c8202a",chest:"#3a4ab0",wing:"#b01a24",tail:"#a01822",beak:"#222"}]],
  day:"Rustige routine, veel vers eten, klimmen en kalm samenzijn; geen druk speeltempo.",
  c:{body:"#3fb24a",head:"#3fb24a",wing:"#3aa044",tail:"#3a9a42",beak:"#f2a23a"}, beak:"bighook", tail:"short", primaries:"#2a5fb0",
  src:["young","wpt","lafeber"] },

{ id:"goffin", nl:"Goffins kaketoe", sci:"Cacatua goffiniana", cat:"Grote papegaaien", cm:"30–32 cm",
  size:3, life:[30,50], noise:5, noiseNote:"Hard krijsen, vooral bij aandachtsbehoefte.",
  handsOn:5, bond:5, clown:5, intel:5, train:5, activity:4, flight:3, social:5, pair:"flex",
  mess:5, bite:4, destruct:5, difficulty:5, space:4, hours:[4,6], beginner:1, cost:5, talk:1, song:0,
  slender:false, bold:4, ground:3, vsBirds:3, hormonal:5,
  tag:"Briljante probleemoplosser die nooit genoeg aandacht krijgt.",
  pros:["Bekend om gereedschapsgebruik — extreem slim","Zeer aanhankelijk","Speels"],
  cons:["Extreme aandachtsbehoefte","Sloopt alles","Veel poederdons","Luid"],
  risks:["Plukken en automutilatie bij frustratie","Hormonale problemen bij te veel knuffelen"],
  pairNote:"Bij één vogel zijn de eisen extreem; ervaren houders kiezen vaak voor gezelschap van soortgenoten.",
  sexNote:"Iris: pop vaak roodbruin, man donker — DNA is betrouwbaarder. Beide geslachten kunnen hormonaal problematisch worden.",
  legal:"CITES Bijlage I / EU-bijlage A: alleen met EU-certificaat.",
  mut:[["Wildkleur",{}]],
  day:"Uren interactie, puzzels, sloopmateriaal, training — en bewust níét te veel knuffelen om hormonale problemen te voorkomen.",
  c:{body:"#f6f4ef",head:"#f6f4ef",crest:"#f6f4ef",cheek:"#f0c0b0",wing:"#efede8",tail:"#ece9e2",beak:"#d8d2c4",eye:"#b8c8d8"}, beak:"bighook", tail:"short", crest:"cockatoo",
  src:["cites","wpt","young"] },

{ id:"dwergara", nl:"Dwergara (roodschouderara)", sci:"Diopsittaca nobilis", cat:"Grote papegaaien", cm:"30–35 cm",
  size:3, life:[25,40], noise:4, noiseNote:"Luid, maar minder dan grote ara’s.",
  handsOn:4, bond:4, clown:4, intel:4, train:4, activity:4, flight:4, social:4, pair:"flex",
  mess:4, bite:3, destruct:4, difficulty:4, space:4, hours:[2,4], beginner:2, cost:4, talk:3, song:0,
  slender:true, bold:4, ground:2, vsBirds:3, hormonal:3,
  tag:"Ara-karakter op handzaam formaat.",
  pros:["Speels en aanhankelijk","Kan woorden leren","Slank en goede vlieger"],
  cons:["Luid","Sloopt","Heeft veel aandacht nodig"],
  risks:["Schreeuwgedrag bij verveling"],
  pairNote:"Eén met veel aandacht, of een paar.",
  sexNote:"DNA nodig.",
  legal:"CITES Bijlage II.",
  mut:[["Wildkleur",{}]],
  day:"Trainen, vliegen, sloopmateriaal en veel samen zijn.",
  c:{body:"#4fa84a",head:"#4fa84a",cap:"#2f6fc0",cheek:"#f2f2f2",wing:"#3f9a3a",tail:"#3f9a3a",beak:"#222"}, beak:"bighook", tail:"verylong", shoulder:"#d23a2a",
  src:["cites","wpt","lafeber"] },

{ id:"ara", nl:"Blauwgele ara", sci:"Ara ararauna", cat:"Grote papegaaien", cm:"80–90 cm",
  size:5, life:[50,70], noise:5, noiseNote:"Extreem luid; draagt honderden meters.",
  handsOn:4, bond:5, clown:5, intel:5, train:5, activity:4, flight:4, social:5, pair:"flex",
  mess:5, bite:4, destruct:5, difficulty:5, space:5, hours:[3,6], beginner:1, cost:5, talk:3, song:0,
  slender:true, bold:4, ground:2, vsBirds:2, hormonal:4,
  tag:"Indrukwekkend en levenslang — letterlijk.",
  pros:["Spectaculair","Zeer slim en speels","Kan diepe band vormen"],
  cons:["Extreem luid","Heeft een kamer/volière nodig, geen kooi","Snavel sloopt meubels","Hoge kosten"],
  risks:["Gedragsproblemen bij onvoldoende ruimte/aandacht","Overleeft vaak de eigenaar"],
  pairNote:"Eén met zeer veel aandacht, of een paar in een grote volière.",
  sexNote:"DNA nodig.",
  legal:"CITES Bijlage II.",
  mut:[["Wildkleur",{}]],
  day:"Een vogelkamer of grote volière, uren interactie, veel hout om te slopen en een plan voor na jou.",
  c:{body:"#f2b02a",chest:"#f2b02a",head:"#2f8fd0",cap:"#3aa060",cheek:"#f4f4f4",wing:"#2a6fc0",tail:"#2a6fc0",beak:"#222"}, beak:"bighook", tail:"verylong",
  src:["cites","young","wpt"] },

{ id:"witkaketoe", nl:"Witkuifkaketoe", sci:"Cacatua alba", cat:"Grote papegaaien", cm:"45–50 cm",
  size:4, life:[40,70], noise:5, noiseNote:"Oorverdovend krijsen.",
  handsOn:5, bond:5, clown:4, intel:5, train:4, activity:4, flight:3, social:5, pair:"flex",
  mess:5, bite:4, destruct:5, difficulty:5, space:5, hours:[4,6], beginner:1, cost:5, talk:2, song:0,
  slender:false, bold:4, ground:3, vsBirds:3, hormonal:5, status:"afgeraden",
  tag:"Afgeraden voor de meeste huishoudens.",
  pros:["Extreem aanhankelijk","Slim"],
  cons:["Verwacht vrijwel constante aandacht","Krijst bij frustratie","Zwaar destructief"],
  risks:["Plukken en automutilatie","Hormonale problemen door overmatig knuffelen"],
  pairNote:"Zelfs met één vogel zelden haalbaar voor een particulier.",
  sexNote:"DNA nodig.",
  legal:"Controleer de CITES-status en papieren bij aanschaf.",
  mut:[["Wildkleur",{}]],
  day:"Vrijwel de hele dag gezelschap en verrijking — voor de meeste mensen niet realistisch.",
  c:{body:"#f8f8f6",head:"#f8f8f6",crest:"#f8f8f6",wing:"#f0f0ee",tail:"#ececea",beak:"#333",eye:"#b8c8d8"}, beak:"bighook", tail:"short", crest:"cockatoo",
  src:["wpt","young"] }
];

if (typeof module !== "undefined") module.exports = { SPECIES, SOURCES, DATA_NOTE };
